---
title: "Del Toro's *Frankenstein*"
subtitle: "Jonathan Romney"
---

_Sight & Sound_, November 2025

It was a dark and stormy night. Torrential rain lashed at the solitary walkers struggling through the empty streets; sheet lightning electrified the sky in abrupt blinding bursts…

OK, we know that Netflix has considerable promotional resources, but surely it was beyond even their capacities to mount so spectacular a weather event on the Venice Lido in the run-up to the Biennale premiere of Guillermo del Toro’s _Frankenstein_. This is the climate you associate with 19th-century Romanticism at its most turbulent, and above all with the Gothic - a mode that del Toro has very much made his own in a filmography spanning 33 years.

There are, however, several forms of Gothic in the Mexican director’s work. One is the Lovecraftian Gothic of the ghastly and tentacular, given full display in his _Hellboy_ films and his TV anthology series _Guillermo del Toro’s Cabinet of Curiosities_. Another is the Gothic imagination that went on to feed cinema’s horror tradition; flourishing in Romantic literature and painting, it found its written expression in novels such as _The Castle of Otranto_, _Melmoth the Wanderer_ and most famously, Mary Shelley’s _Frankenstein, or the_ _Modern Prometheus_. The iconography of dark houses and darker passions fed the Hollywood melodrama too, beyond horror per se – thereby informing del Toro’s period piece _Crimson Peak_ (2015) and even his neo-noir drama _Nightmare Alley_ (2021).

But the purest form yet of del Toro’s reimagined High Gothic is his spectacular new addition to cinema’s Frankenstein canon – which he has described as a melodrama, rather than a horror film. It may include homages to, and inescapable residues of, screen horror history, but above all it draws inspiration directly from Shelley’s novel. The film takes its debt to the English Romantic wellspring very seriously indeed, and if its bravura maximalism sometimes leaves it open to accusations of kitsch or bombast, its imagination and energy are undeniable and extremely alluring.

This is a labour of love, to say the least: del Toro has been fascinated with the Frankenstein story and its imagery ever since seeing James Whale’s classic 1931 film at the age of seven. Del Toro’s version is correspondingly dense with themes and echoes, literary, filmic and pictorial: the poetry of Percy Bysshe Shelley and Lord Byron; a host of art-historical allusions; visual nods to Murnau, the Hammer horror cycle et al; and to the 1983 Frankenstein illustrations of comics/horror artist Bernie Wrightson, an avowed influence. Del Toro’s script is also densely patterned with central themes of 19th-century history (prosthetics, syphilis, early photography, the Crimean War).

His version of the story is also a very Freudian saga. Hubris-ridden scientist Victor Frankenstein (Oscar Isaac) - the ultimate Flawed Father, second only to God - is motivated partly by his animus against an authoritarian patriarch (Charles Dance), but behaves even more monstrously to his own abhorred, abandoned creation (Jacob Elordi). Inescapably, the film comes across as a thematic companion piece to del Toro’s recent stop-motion _Pinocchio_, with Victor as a warped version of woodcarver Geppetto, and the Creature as the handmade being on a journey to become a ‘real boy’ – i.e. a complete human rather than a patchwork composite. If this makes his 149-minute epic seem the proverbial ‘large loose baggy monster’, that’s altogether appropriate for a film stitched from disparate parts, as much a grotesque, singular amalgams its misbegotten protagonist.

​Few film-makers manifestly relish holding forth about their work as much as del Toro famously does; sitting in a suite in the Lido’s Excelsior Hotel, he’s less like a film-maker simply promoting his latest product, more like a genial, enthusiastic guide providing a tour of the vast haunted manor of his themes and obsessions.​​

“This is a movie I’ve been pursuing for decades. I was pursuing it actually before I had a camera, as a kid - as soon as I learned what directing was, that’s the movie I wanted to make. I was very stringent with not trying it earlier until I was about 40, because I didn’t feel prepared, I didn’t feel brave or foolish enough to do it. But I knew I wanted to make it like a great handmade operatic production. It needed to be lush, and it needed to feel modern - I didn’t want to do a Merchant-Ivory pastel, safe Victorian era. I wanted to be a little more vivid, a little more innovative.”

His _Frankenstein_ melodrama, del Toro says, is “a family movie - a father-and-son ‘generational pain’ story. Over the years, it became very biographical for me - not that I created a monster, or my father hit me across the face, but because you grow under the shadow of a father anjd you become that father without realising it. That was very personal, and I always felt if I had done it younger, I would have done only the story of the son. But doing the story of Victor becoming his father and the creature becoming Victor is what I found very inspiring.

“Of course it’s horror, of course it’s science fiction, it’s all these things, because the source is that. But the more you know of the Mary Shelley novel, the more you see how biographical it is for her. I thought, ‘You have absorbed the novel, you have absorbed her life - make it biographical to you, as sincerely and unguardedly, as she did’” (biographical readings of _Frankenstein_ have often focused on the death of Mary’s premature first child in 1815, when she was 17).

​The film is authentically rooted in the structure of Shelley’s novel, beginning and ending like hers amid the ice floes of the far north. “The Arctic for me,” del Toro says, “is a perfect existential theatre of the mind.” The frozen wastes are at once a vision of the infinite and a prison. The ice-locked ship, in novel and film, echoes the blockage that Mary experienced at the Villa Diodati in Switzerland in 1816, when she, Percy Shelley, Lord Byron and others decided to devise ghost stories: she struggled to think of anything, until the famous dream that unlocked her imagination. Del Toro is also faithful to the novel’s juxtaposition of high-flown visionary idealism and the basely material: Victor’s dream of new life and his grisly _bricolage_ of entrails and decay; the themes of love and desire against the omnipresence of death (crystallised in the theme of syphilis, which affects one character).

​“The very spirit of the Gothic is the marriage of death and love,” says del Toro, “the sublime and the corrupt - graveyard poetry, the sense of doom in the ruins lending them beauty. The Gothic novels are inspired by Piranesi’s engravings of the Roman ruins” – 18th-century images which became a key influence in the development of the Gothic sense of space. “The edifice and ruins become an avatar of the human mind. Every great piece of Gothic literature has this element.”

​Shelley’s novel is best known in its standard 1831 edition, but del Toro has a special fondness for the initial version of 1818: “It’s a lot more undisciplined, but it’s the one I like the most, because she is tackling social injustice, capitalism, travelogue, adventure stories, science. She is insatiably curious, and she merges all these things into one tale. When you are in your teens and you read _Frankenstein_, it’s the greatest book ever written, because it has the same hunger than you have intellectually as a kid.”

​Del Toro’s script structures the narrative as a doppelganger story in two chapters: Victor’s narrative, then the Creature’s, both framed by their encounter in the Arctic, as witnessed by the crew of a Danish ship, its captain played by Lars Mikkelsen. The diptych structure, derived from the novel, establishes creator and creature not just as parent and child, but as quasi-brothers - both essentially naïve children, each embarked on his own agonised journey of apprenticeship.

Victor’s tale is carried off with bracing dash, not least thanks to Oscar Isaac’s genially vigorous performance, his scientist a flamboyant showman enthusiast, seen in a lecture theatre passionately defending his theories. In a key sequence, Victor is seen hand-stitching and carving his creation out of scattered body parts, in a grisly, grandiose but oddly exuberant _danse macabre_ scored by Alexandre Desplat (the sequence inescapably echoing del Toro’s own origins as a special effects maestro with a commitment to the handmade).

​“I wanted Victor to be a rock star,” he says. “He’s very Paganini, or Liszt - the rock stars of concerto. And I shot his lecture like a concert, the same way as the creation (of the Creature), which is rarely, if ever, shown on film. I wanted to make an anatomical waltz. It’s not a horror sequence. It’s a joyous sequence of him patching and cutting and stitching - it’s really the most vitalist scene in the film.”

​The Creature, meanwhile, is played by Jacob Elordi, stepping into a role originally to be played by Andrew Garfield, until he dropped out because of scheduling problems. Elordi’s casting brings an extra dimension to the role, given the actor’s intensely sexualised heartthrob image (_Saltburn_, _Euphoria_, Elvis in Sofia Coppola’s _Priscilla_). The well-carved features we see gradually emerging from the Creature’s jigsaw physiognomy suggest a Luciferian fallen angel, with an androgyny that picks up on the sexual ambiguity of the 1930s Universal films – their Dr Frankenstein played as a ‘feminised’ intellectual by Colin Clive, while _The Bride of Frankenstein_ introduced a figure of outright queerness in Ernest Thesiger’s frenetically camp Dr Pretorius.

Elordi’s Creature is first glimpsed as an embodiment of monstrous hyper-masculinity, roaring beast-like in the Arctic, indestructible and preternaturally strong. But in the flashback to his ‘birth’, he is child-like, vulnerable, delicate in his movements – the result of Elordi’s several weeks of training with a Japanese _butoh_ teacher. “I told Jacob, ‘When you have the tools you need, you can call it a day. I don’t want you to become a _butoh_ dancer, I want you to know the basics.’ He did things with his shoulder and with his neck and his waist that disarticulated them in a great way.”

​Elordi’s characterisation of the Creature is all about sexual ambivalence, and indeed multiplicity, given the creature’s literally composite nature: this ‘it’ is at heart the ultimate ‘they’. Del Toro’s film depicts two thwarted romances: one between Victor and his creation, the other between the Creature and Victor’s prospective sister-in-law Elizabeth(Mia Goth), the only person who understands this being.

​“Ambiguity is one of the great virtues of Romanticism. Gothic is both sensorial - sensual - and spiritual. The ‘other’, quote unquote, is always present in horror and Gothic romance – and always in a light that renders it not as something to be afraid of, but as something to recognise in yourself. There is great beauty to that, and a great liberation.”

​Elizabeth – in this version, engaged not to Victor but his brother – is at the centre of the film’s play of death and desire. As well as bringing an explosion of colour and light to an otherwise dark, downbeat palette - thanks to Kate Hawley’s vividly fanciful costume design – it is Elizabeth who activates its dialectic of desire and death.

Elizabeth is also something of a surrogate for Mary Shelley, with her philosophical insight and warnings to Victor about the folly of his ambitions. She is the one character in the film who really knows the score about both love and death. This is evoked brilliantly in a sly visual echo: at one point we see Elizabeth’s uncle, the arms dealer Harlander (Christopher Waltz) posing a thinly-clad young woman holding a peach for one of his soft-erotica photographs (in classical iconography, notes del Toro, “the peach, depending on the painting, represents both female anatomy and youth.”) When we first see Elizabeth, it’s in an echo of that shot: she’s in the exact same pose, but holding a skull.

​The element of perversity in Elizabeth – who comes to both despise and (quasi-incestuously) desire Victor – is all the more vivid because she is played by Mia Goth, who was a fearsome embodiment of libido, violence and downright weirdness in Brandon Cronenberg’s _Infinity Pool_ and Ti West’s _X_ trilogy. Goth’s performance in Frankenstein is uncharacteristically formal, even stiff - but that makes her ambivalent connection with both Victor and his creation all the more intensely charged.

​“Except for Jacob, who came late into the production,” del Toro says, “every single part in the movie was scripted for the actor playing it, and Mia was no exception. The original cut was three hours 40, so there’s a lot more to Elizabeth than what is in the final version. There was a lot more about her time in the convent, and her adoration of Jesus’s statue with a wound on his flank, which is the same wound the Creature has.”

​The resonances of the Frankenstein myth have continued to fascinate ever since the book’s first publication – the novel in its time was interpreted as a horrific parable of social uprising in the wake of the French Revolution, and subsequent 20th and 21st century versions have been comprehensively mined for subtexts relating specifically to their moment. Frankenstein forever endures as the quintessential Science Gone Too Far scare story, but del Toro rejects any suggestion that his version might be a 2020s commentary on the rise of AI (although Shelley’s Creature very much functions like a Large Language Model, its own self-awareness and floridly crafted verbal skills emerging from its ‘programming’ itself by reading _Paradise Lost_ and Goethe’s _Young Werther_).

Del Toro denies any reference to AI, but adds, “Now, if somebody reads it like that… Once you put the letter out, it’s the reader that owns it, not the writer. I discount it because I have nothing but joy that I’m going to die before AI takes over any lives. For me, AI can do many things that are all transhumanistic, and I’m not interested that much in transhumanism, not as a pursuit I want to entertain.”

​There are, however, hints at transhumanism in the film’s motif of prosthetics: wounded in an explosion, Victor uses an artificial leg, while the Creature itself might be seen as a living prosthetic for its maker’s soul, or psyche.

​ “To me it’s always been very interesting,” del Toro says, “to have a character that little by little becomes that which he or she thinks they’re not. The villains in _Pan’s Labyrinth_ or in _The Devil’s Backbone_ get disfigured or maimed into becoming more accurately who they are. But they start as beautiful - sort of Luciferian creatures. Victor also becomes an artificial man in a way, with the limb and with his not understanding that the creature is not an extension of himself, but something different. Which I think is the root of all bad paternal relationships - believing that your kids are an accessory to you, or an extension of you.”

​As much as his _Frankenstein_ is a Freudian, certainly Oedipal story, it is also, del Toro stresses, a very Catholic film. Haunted in his sleep by a nightmare angel figure, Victor at one point sneaks into a church’s confessional booth to listen to Elizabeth (Mia Goth) profess her hatred of him (for which read; veiled passion).

​“I think my cosmology is a Catholic cosmology – from _Cronos_ on, with the main character called Jesus and resurrecting on the third day. I cannot avoid that. I was raised that way. I’m not a believer, I’m not a churchgoer, but the cosmology weighs very heavily on me.

“And I’ve always wondered why God, who knows all, sent His son to be crucified” (indeed, when del Toro’s Creature is about to come to life – or, being composed of dead matter, resurrected – we see him in an overt crucifixion pose). “And I believe He was interested in death and pain, you know, to experience it. That’s what I wanted to echo with Victor.”​

​So, God as a sadistic film-maker? “Or a mad scientist,” Del Toro laughs. “One of the things that I find very moving is that Victor decides to serve life, and the archangel reveals himself to be Death at the end - that’s who he has been serving.”

​This servitude to Death is intimately linked with the film’s depiction of capitalism run riot. Victor’s ostensible idealism and dream of conquering mortality are backed by the wealthy Henrich Harlander, a 19th-century financier and arms dealer. Harlander is also an early enthusiast for photography, which he explores as a creator of amateur erotica.

​“When I was a young filmmaker in the '90s,” del Toro remembers, “a very wise man who was in charge of VHS, and later laser discs and DVDs, said to me, ‘The first adopter of a new technology is porn, the last adopter Disney.’ (Laughs) He said, ‘Don’t buy the hardware until Disney has it!’

“One of the things I - jokingly, but very earnestly - tried was to make Victor a film-maker and Harlander the studio. The thing they have in common is a moment in which they do something that sounds like a good idea at the time, and has consequences.”

​Another key political resonance in the film is the theme of war and its devastation, with Victor using the battlefields of Crimea as an endlessly replenished source of recyclable cadavers. In this sense, the film illustrates the loop uniting technology and war: for military technology to constantly advance, it needs more people to die as it perfects the next generation of armaments.

“That’s where I would amend my friend’s quote - the first adopter is war. Because for me, the Industrial Revolution’s first consequences are of war.” Del Toro muses: “I never understood, why did Victor make a man out of so many parts? Why not find two halves that work, or three pieces? And my answer was simple. The purveyor is war. War is always birthed out of ideals that have no real consequences or results. When you talk about country and valour and heroism and the motherland, then you end up committing atrocities.”

​You end up with the mountain of bodies in the charnel house. “Which is exactly what Victor does. It starts as, ‘I want to combat death’, and then he’s pushing piles of remains out of a chute into a lake. The dirt that follows the altruistic is always trailing blood.”

​Regardless of the ghoulish content, del Toro’s _Frankenstein_ also cultivates a striking and densely-patterned visual beauty. Texture in particular has always been a constant with the director, whose feel for special effects is very much focused on materiality, the tactile – and on surprise.

“I told Mike Hill, who was creating the monster with me, “Don’t rewatch any of the classics. Either you have them in your DNA, and then that’s great…” No one’s gonna top Jack Pierce [creator of the original 30s _Frankenstein_ make-up] and Boris Karloff.”

​Instead of mainstream _Frankenstein_ references, the film is patterned with art-historical allusions, including the anatomical models of 17th-century wax sculptor Gaetano Zumbo (“Amazing flayed Venuses, exhibiting all the organs - they look like a Bernini Saint Teresa”) and the illustrations of 16th-century anatomy pioneer Andreas Vesalius. The latter’s images are even, as it were, encrypted into the very textures of the film’s costumes: “We used some Vesalius in the weaving of the fabrics. We have mineral patterns, butterfly wing patterns, anatomical patterns. Every piece of fabric on the main characters - we wove most of them.”

This perfectionism may reach a special peak in the making of a film especially close to del Toro’s heart. But it is generally characteristic of his desire to imprint his personal signature on the fictions he takes on, and transforms. “It’s the same thing I feel about any other defined genre, literary or filmic. If you only do the clichés - if you do noir, and you do the blinds and the fedoras and the wet streets and that’s all you do - then you’re doing a pastiche. But if you go back to the social injustice, the rage that gives birth to noir, then you are really drawing on the roots.

“What I’ve tried to do all of my life, from _Cronos_ on, is take identifiable genres, sometimes hallowed, sometimes not, and try to renew them. If I tackle a fairy tale, I want to do it in a different way from other film-makers, if I tackle a ghost story, I set it in an orphanage in the middle of a desert in Spain [_The Devil’s Backbone_]. I don’t want to do a giant robot versus a giant monster [2013’s _Pacific Rim_] by the book - I want to treat it as a journey of recovery of somebody that has childhood trauma. People can enjoy it just as a romp, or they can see more into it. I know what I put in. That doesn’t mean that’s what they read.”

As a dream project finally realized, del Toro’s _Frankenstein_ has in some ways become an allegory of its own creation. What is Victor, after all, when he stitches the Creature together, or finally animates it during the time-honoured lightning storm, but a version of del Toro himself as driving force behind the long gestation and ultimate unveiling of his film? That makes it all the more poignant to witness Victor’s exhaustion on beholding his Creature – not, apparently, the quintessence of superhuman possibility, but a shambling, unformed, inarticulate thing. Overcome with anti-climactic despair, Victor laments that his long-cherished achievement is “void of meaning.” You can’t help wondering whether del Toro felt the same way on wrapping his film.

​“That’s exactly why I wrote it. Most of the dialogue is not from the book, it’s a dialogue with myself. So that line I wrote specifically for me. Because I think that’s true of revenge, of artistic merit - once the deed is done, the void follows. You can call it postpartum depression.”

Indeed, he says, this film marks an ending for him, a fulfilment and an exhaustion of certain possibilities. “_Frankenstein_ is for me the final movie in a style that I’ve been pursuing for 30 years. I cannot make a movie more my movie than _Frankenstein_. All those stylistic ways of operating sets or moving the camera in a way that is almost dance-like - all that comes to an end on this movie.”

What’s next for del Toro is something entirely different and rather smaller, a crime thriller called _Fury_, “essentially a dialogue of good and evil between two men. It’s based on a Spanish movie, _The Fury of a Patient Man_ by Raúl Arevalo [2016]. I saw that movie and I thought, ‘First and second act I adore, and I can create a third act that that is completely new, or that leads to a different place.’”

It was a dinner with David Cronenberg, del Toro says, that provided a clue to the art of renewing yourself when you’re deep into a long career. “He said, ‘Look, one part of you goes away, and then it’s up to you… You still carry your style, you still carry your substance, but you need to scare yourself back.’ All you have is the chance to go to a style that scares you - abandon a lot of the frills and thrills that made you want to do things, and go in a new direction. And that’s what I’m trying to do.”

----------

SIDEBARS

_THE SPIRIT OF THE BEEHIVE_

In Victor Erice’s 1973 Spanish classic, a young girl is haunted by her viewing of James Whale’s _Frankenstein_; its echoes resound in del Toro’s _Pan’s Labyrinth_ (2006). Whatever my garden is, it has been growing in the shade of that movie. I can tell you, the two steps of becoming who I am were seeing Frankenstein at seven and _The Spirit of the Beehive_ in my teen years. I thought the effort apparently effortless, the way in which Erice paraphrases the novel and the horrors of childhood - that became my path. I knew I would do it differently, I knew I would do it in my own way, but I knew that in that horizon lay the promise of a new land.

HAMMER HORROR

There are homages to Christopher Lee being shot in the face (The Curse of Frankenstein, 1957), and Dracula sinking into the ice (Dracula: Prince of Darkness, 1966). I very much like the elegance of Terrence Fisher in all his movies, The Curse of the Werewolf to me being the best. And in a very different way, I like the sociopath aspect of Peter Cushing’s Baron. I adore it. And he has a similar origin story. He basically kills his father, his tutor, his guardian, to get all the money to do his experiments. The most terrifying monster in all the Hammer Frankenstein movies is the Baron.

SILENT CINEMA

(Jacob Elordi and I) watched a lot of silent cinema. I said, “Look at Emil Jannings [in Murnau’s _Faust_], how he trails his hands back. There’s a scene in _Faust_ that I reference for Harlander, where the Devil, Mephistopheles, greets Faust and tips his hat - he’s very menacing.

OLIVER REED

I told Oscar he should watch Oliver Reed. When Oliver Reed emotes, people say, “Oh, he’s very big,” – and I say, “Yeah, but there’s modulation.” There is a symphonic nature to him, but when he’s low (does a deep raspy Reed voice), when he talks to Sister Jeanne [in Ken Russell’s _The Devils_], when he talks to the judges at the end, he goes low…