---
title: "spectral cinema"
subtitle: "retratos fantasmas"
---

{{< video https://youtu.be/4cfogyfMnho >}}

**Retratos Fantasmas** [Pictures of Ghosts] (Kleber Mendonça Filho, 2023)

## The Phantom Taxi Driver

In the final sequence of **Retratos Fantasmas**, Kleber Mendonça Filho's film about the movie theaters of Recife of his youth, we see the filmmaker crossing a road at night with his cellphone and getting into an Uber. After a brief exchange about why he's requested three stops along the route (he likes to unwind by being driven around rather than just going straight home), they segue into a discussion of the music the driver is playing - a track by jazz trumpet legend Herb Alpert - and the driver is impressed to hear that Kleber is a filmmaker. At this point the driver informs him that he recently discovered that he has a superpower: the ability to become invisible. Unphased, Kleber asks him whether he can do so deliberately or if it happens by accident in the middle of a conversation. After some further discussion, the diegetic music fades up as the film cuts between close-up shots of Kleber in the back of the taxi, the driver, and POV views of the nocturnal city scrolling past the window, until a POV shot from Kleber's perspective shows that the driver has disappeared and the car appearing to drive itself. Intrigued, Kleber leans forward to confirm that the driver has vanished, and we see several similar shots to the earlier close-ups that had previously shown the driver, now occupied only by the headrest. Disconcerted by this apparent confirmation of the driver's superpower, Kleber reaches for his seatbelt before confirming verbally the continuing presence of the driver. In a final close-up, the semi-transparent images of the invisible driver partly fades back into view before the film wraps with a dreamy montage of POV views of the nocturnal city, to Herb Alpert's 1980s disco soundtrack. Credits.

## Spectral Cinema

Running around 8 minutes, the sequence could easily stand alone as a short in its own right. While undeniably "cinematic" in the contemporary sense, it could easily be dismissed as a whimsical coda to what had been up to that point a fairly conventional personal and historical documentary. Far from being merely tacked on, though, I would argue that the sequence serves as a playful metaphor for the same themes of wistful disappearance and cinematic nostalgia that the earlier sections of the film have been exploring. Like the Uber sequence, those sections are also about vanishing: the vanishing movie palaces of another time, when Hollywood A-listers strolled the sidewalks and people flocked to see the American blockbusters of their day,  now repurposed as shopping centers and even evangelical churches, with only relics remaining: posters, photos of marquees, ancient projectors on display like historical artefacts. Now you see it, now you don't; yet as the film shows, by its own special magic, cinema is able to conjure up apparitions of these ghosts of cinema past for us, like the eighteenth-century phantasmagorias that were their their historical predecessors. At the height of the age of social media, cinema continues to haunt us, a ghostly apparition flickering across the walls of once thronging but now empty, silent movie theaters, enabling us to commune with the spirits of the past. As its title makes clear with its invocation of ghostly portraits, the film is suffused with  themes of the paranormal: unnatural events, haunted spaces, spectral presences: the cover of the scanner that mysteriously drops as the filmmaker talks about the photograph of a ghost that he accidentally took, and how people think he is a medium; or the ghost dog from the building next door that appears in his atmospheric earlier film **O Som ao Redor** [Neighboring Sounds] (2012), which he hears barking one night and thinks it has returned from the dead, only to realize that the sound comes from a TV in a neighboring apartment where someone is watching the very film that was made there. It's a perfect example of what the British cultural critic Mark Fisher would call hauntological cinema. In that sense it's only one of many films that explore cinema's capacity to conjure up the past, movie theaters as haunted spaces, from the Overlook Hotel of **The Shining** to Tsai Ming-Liang's **Goodbye, Dragon Inn** (2003), to Olivier Assayas's **Personal Shopper** (2016).

## The Cinematic Experience

More than anything else, though, Retratos Fantasmas conjures up the image of cinema not as reels of celluloid or old projectors, but as a collective cultural experience: the film is awash with images of the movie audiences that Kleber himself was a part of, lining up around the block to see the latest Hollywood monster movie, or packing the elaborately designed screening halls. This connects the film back to other films that do this, like **Cinema Paradiso** (Giuseppe Tornatore, 1988) or the screening of **Frankenstein** in a remote Spanish village in **El Espíritu de la Colmena** [The Spirit of the Beehive] (Victor Erice, 1973) (shown in the Film History class, fall 2025). It is, in this sense, the perfect medium for conjuring up its own history, even as in the twenty-first century it migrates to other media and platforms. In this sense, then, **Retratos Fantasmas** is a reflection not just on Kleber's own experience of cinema and his own films that grew out of it, but on the nature of cinema itself.



